import { env } from './validation';

export const buildChainsConfig = () => ({
  ethereum: {
    id: 1,
    name: 'Ethereum',
    symbol: 'ETH',
    rpcUrl: env.ETHEREUM_RPC_URL,
    nativeCurrency: { name: 'Ether', symbol: 'ETH', decimals: 18 },
    blockTime: 12000,
    gasMultiplier: 1.1,
    enabled: !!env.ETHEREUM_RPC_URL,
  },
  polygon: {
    id: 137,
    name: 'Polygon',
    symbol: 'MATIC',
    rpcUrl: env.POLYGON_RPC_URL,
    nativeCurrency: { name: 'Matic', symbol: 'MATIC', decimals: 18 },
    blockTime: 2000,
    gasMultiplier: 1.2,
    enabled: !!env.POLYGON_RPC_URL,
  },
  arbitrum: {
    id: 42161,
    name: 'Arbitrum One',
    symbol: 'ARB',
    rpcUrl: env.ARBITRUM_RPC_URL,
    nativeCurrency: { name: 'Ether', symbol: 'ETH', decimals: 18 },
    blockTime: 1000,
    gasMultiplier: 1.05,
    enabled: !!env.ARBITRUM_RPC_URL,
  },
  optimism: {
    id: 10,
    name: 'Optimism',
    symbol: 'OP',
    rpcUrl: env.OPTIMISM_RPC_URL,
    nativeCurrency: { name: 'Ether', symbol: 'ETH', decimals: 18 },
    blockTime: 2000,
    gasMultiplier: 1.05,
    enabled: !!env.OPTIMISM_RPC_URL,
  },
  base: {
    id: 8453,
    name: 'Base',
    symbol: 'BASE',
    rpcUrl: env.BASE_RPC_URL,
    nativeCurrency: { name: 'Ether', symbol: 'ETH', decimals: 18 },
    blockTime: 2000,
    gasMultiplier: 1.05,
    enabled: !!env.BASE_RPC_URL,
  },
  bsc: {
    id: 56,
    name: 'BNB Smart Chain',
    symbol: 'BNB',
    rpcUrl: env.BSC_RPC_URL,
    nativeCurrency: { name: 'BNB', symbol: 'BNB', decimals: 18 },
    blockTime: 3000,
    gasMultiplier: 1.1,
    enabled: !!env.BSC_RPC_URL,
  },
  avalanche: {
    id: 43114,
    name: 'Avalanche',
    symbol: 'AVAX',
    rpcUrl: env.AVALANCHE_RPC_URL,
    nativeCurrency: { name: 'Avalanche', symbol: 'AVAX', decimals: 18 },
    blockTime: 2000,
    gasMultiplier: 1.1,
    enabled: !!env.AVALANCHE_RPC_URL,
  },
  fantom: {
    id: 250,
    name: 'Fantom',
    symbol: 'FTM',
    rpcUrl: env.FANTOM_RPC_URL,
    nativeCurrency: { name: 'Fantom', symbol: 'FTM', decimals: 18 },
    blockTime: 1000,
    gasMultiplier: 1.1,
    enabled: !!env.FANTOM_RPC_URL,
  },
});

