import { SensitiveSecrets } from './validation';

export const buildChainsConfig = (secrets: SensitiveSecrets) => ({
  ethereum: {
    id: 1,
    name: 'Ethereum',
    symbol: 'ETH',
    rpcUrl: secrets.ethereumRpcUrl,
    nativeCurrency: { name: 'Ether', symbol: 'ETH', decimals: 18 },
    blockTime: 12000,
    gasMultiplier: 1.1,
    enabled: !!secrets.ethereumRpcUrl,
  },
  polygon: {
    id: 137,
    name: 'Polygon',
    symbol: 'MATIC',
    rpcUrl: secrets.polygonRpcUrl,
    nativeCurrency: { name: 'Matic', symbol: 'MATIC', decimals: 18 },
    blockTime: 2000,
    gasMultiplier: 1.2,
    enabled: !!secrets.polygonRpcUrl,
  },
  arbitrum: {
    id: 42161,
    name: 'Arbitrum One',
    symbol: 'ARB',
    rpcUrl: secrets.arbitrumRpcUrl,
    nativeCurrency: { name: 'Ether', symbol: 'ETH', decimals: 18 },
    blockTime: 1000,
    gasMultiplier: 1.05,
    enabled: !!secrets.arbitrumRpcUrl,
  },
  optimism: {
    id: 10,
    name: 'Optimism',
    symbol: 'OP',
    rpcUrl: secrets.optimismRpcUrl,
    nativeCurrency: { name: 'Ether', symbol: 'ETH', decimals: 18 },
    blockTime: 2000,
    gasMultiplier: 1.05,
    enabled: !!secrets.optimismRpcUrl,
  },
  base: {
    id: 8453,
    name: 'Base',
    symbol: 'BASE',
    rpcUrl: secrets.baseRpcUrl,
    nativeCurrency: { name: 'Ether', symbol: 'ETH', decimals: 18 },
    blockTime: 2000,
    gasMultiplier: 1.05,
    enabled: !!secrets.baseRpcUrl,
  },
  bsc: {
    id: 56,
    name: 'BNB Smart Chain',
    symbol: 'BNB',
    rpcUrl: secrets.bscRpcUrl,
    nativeCurrency: { name: 'BNB', symbol: 'BNB', decimals: 18 },
    blockTime: 3000,
    gasMultiplier: 1.1,
    enabled: !!secrets.bscRpcUrl,
  },
  avalanche: {
    id: 43114,
    name: 'Avalanche',
    symbol: 'AVAX',
    rpcUrl: secrets.avalancheRpcUrl,
    nativeCurrency: { name: 'Avalanche', symbol: 'AVAX', decimals: 18 },
    blockTime: 2000,
    gasMultiplier: 1.1,
    enabled: !!secrets.avalancheRpcUrl,
  },
  fantom: {
    id: 250,
    name: 'Fantom',
    symbol: 'FTM',
    rpcUrl: secrets.fantomRpcUrl,
    nativeCurrency: { name: 'Fantom', symbol: 'FTM', decimals: 18 },
    blockTime: 1000,
    gasMultiplier: 1.1,
    enabled: !!secrets.fantomRpcUrl,
  },
  solana: {
    id: 'solana',
    name: 'Solana',
    symbol: 'SOL',
    rpcUrl: secrets.solanaRpcUrl,
    heliusApiKey: secrets.heliusApiKey,
    enabledProtocols: (process.env.SOLANA_ENABLED_PROTOCOLS || 'jupiter,marinade,orca').split(','),
    nativeCurrency: { name: 'Solana', symbol: 'SOL', decimals: 9 },
    blockTime: 400,
    gasMultiplier: 1.0,
    enabled: !!secrets.solanaRpcUrl,
  },
});

